### ISSUE TITLE
Getting an external microphone to work

### ISSUE THREAD

**Issue by jasonthenderson** [Xinyuan-LilyGO/T-TWR#10]
Do I actually need to remove the built-in microphone to get the external microphone to work, or could I just put some tape over the built-in microphone to prevent sound from getting to it?

If I do need to remove the built-in microphone are there any tips on how to best do this?  Do I heat it up with a soldering iron and try to remove with tweezers?  I understand it is 'do at your own risk' but was wondering if anyone had tried this and had any tips?

**Comment by lewisxhe** [comment]
If you want to use an external microphone, you need to remove the microphone from the TWR board to work properly. Two microphones connected in parallel may also work, but the bias voltage may be incorrect.

You can only use a heat gun to remove the TWR microphone, not a soldering iron.
