### ISSUE TITLE
Wifi not working after reflash with factory firmware

### ISSUE THREAD

**Issue by DL1DRK** [Xinyuan-LilyGO/T-TWR#13]
Dear all,

after a reflash to factory firmware the Wifi is no longer working. Tried to flash again the APRS-firmware, Display shows Wifi on, but will not connect to an existing network or will not provide an accesspoint.

Any clue? Any help?

**Comment by lyusupov** [comment]
https://github.com/nakhonthai/ESP32APRS_T-TWR/discussions
