### ISSUE TITLE
Pinmap diffs between v2.0 and v2.1

### ISSUE THREAD

**Issue by babobba** [Xinyuan-LilyGO/T-TWR#14]
What are the differences and where can I find v2.0 and 2.1 labeled diagrams? 

Talking to lily-go sales, it looks like that only v2.0 is being sold. Is 2.1 still in design ?

**Comment by lyusupov** [comment]
> can I find v2.0 and 2.1 labeled diagrams?

<br>

![](https://raw.githubusercontent.com/lyusupov/SoftRF/master/documents/images/ham-29.jpg)

**Comment by lyusupov** [comment]
> Thanks for the link.

<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">
