### ISSUE TITLE
T TWR Rev 2.1 WiFi Password for NiceRF Factory Firmware

### ISSUE THREAD

**Issue by WH3080** [Xinyuan-LilyGO/T-TWR#16]
Today I received the above referenced product. After putting the system, I scrolled through the menus and found a Wi-Fi menu. I did turn on the Wi-Fi. The Wi-Fi is picked up on my smart phone however I could not find the password to join the Wi-Fi created by the board, please provide the password to join the T TWR 2.1 built in WiFi. I want to emphasize that I did not install any third party software / firmware.

**Comment by lyusupov** [comment]
<img width="685" alt="image" src="https://github.com/user-attachments/assets/cf50fc4d-e1d4-414f-9419-055f14b7794e">

**Comment by WH3080** [comment]
Thank you! 🙏

**Comment by lyusupov** [comment]
<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">
