### ISSUE TITLE
Rotary Encoder Pins

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/T-TWR#18]
I get Pin_A and Pin_B of the rotary definitions for the T-TWR

is any of them like DT and CLK of the rotary encoder libraries available?

**Comment by lewisxhe** [comment]
Of course, the essence is a rotary encoder

**Comment by richonguzman** [comment]
> Of course, the essence is a rotary encoder

do you know which is DT ? to get the code right to test it ?

**Comment by lewisxhe** [comment]
A = CLK  , B = DT

**Comment by richonguzman** [comment]
> A = CLK , B = DT

thanks a lot! im closer and closer for getting all working!
