### ISSUE TITLE
T-TWR RF module connect audio to ESP32

### ISSUE THREAD

**Issue by redfast00** [Xinyuan-LilyGO/T-TWR#2]
Hi! I'd be really excited to use the T-TWR module for digital HAM radio projects (for example as an APRS modem). Is the RF chip directly connected to the microphone/speaker? Is it possible to send and receive audio waveforms from/to the ESP32?

**Comment by redfast00** [comment]
This would for example also make it possible to build an internet-connected radio repeater

**Comment by lbuque** [comment]
> Is the RF chip directly connected to the microphone/speaker?

yes.

> Is it possible to send and receive audio waveforms from/to the ESP32?

Newer hardware may support it.

**Comment by lyusupov** [comment]
> Is it possible to send and receive audio waveforms from/to the ESP32?

https://github.com/Xinyuan-LilyGO/T-TWR/blob/master/schematic/T-TWR-Plus_Rev2.0.pdf

> excited to use the module for digital HAM radio projects (for example as an APRS modem)

https://github.com/erstec/APRS-ESP
