### ISSUE TITLE
T-TWR 3D model case and schematic 

### ISSUE THREAD

**Issue by kkwestt** [Xinyuan-LilyGO/T-TWR#3]
Please add T-TWR 3D model case and schematic. Thx

**Comment by lbuque** [comment]
@kkwestt The schematic diagram has been uploaded, and the 3d model still needs time.

**Comment by F4VSJ** [comment]
Well since February 16th, still no 3d printable case available?
I'm not able to design, sorry

**Comment by lewisxhe** [comment]
Currently, there is still no

**Comment by EasyOne2030** [comment]
**T-TWR 3D model case ?**
