### ISSUE TITLE
print_wakeup_reason' was not declared in this scope

### ISSUE THREAD

**Issue by EasyOne2030** [Xinyuan-LilyGO/T-TWR#4]
exit status 1
'print_wakeup_reason' was not declared in this scope
![2023-04-21_202308](https://user-images.githubusercontent.com/113257866/233708628-2033c47d-ae29-4cf6-8404-941cb799a704.png)
![2023-04-21_202332](https://user-images.githubusercontent.com/113257866/233708654-1c661255-9868-405c-9c7f-6ebd29c47ca5.png)

**Comment by lewisxhe** [comment]
Add this line above the sketch

void print_wakeup_reason();

**Comment by EasyOne2030** [comment]
The problem is not solved !
exit status 1
'app_nvs_init' was not declared in this scope

![2023-04-22_121858](https://user-images.githubusercontent.com/113257866/233778137-0378a870-2666-4f03-87ed-5d8ff31cc7f1.png)

**Comment by lewisxhe** [comment]
Already fixed.

https://github.com/Xinyuan-LilyGO/T-TWR/commit/1597e8b1bccb8b3283aace25060cdb846f4086b7
