### ISSUE TITLE
PTT button is not turn on transmission 

### ISSUE THREAD

**Issue by nmuntyanov** [Xinyuan-LilyGO/T-TWR#5]
Hello, guys!
I've bought TWR Plus 2.0 VHF version, and found few bugs (or not, not shure)

1 transmit/receive frequency can't be changed with encoder via settings menu
I have build firmware in debug mode, and see that new frequency is sent to SA868 but there is still old one on LCD screen

2 there is no transmission when PTT button is pressed
I have added Serial.print in void SA868::transmit() function to be able to debug that it is invoked and it does, but no transmission happened (I have SDR to monitor)

Is anyone have such issues? Any solutions? 

And one more thing, how can i suppress such log types:
```
$GNGSA,A,3,09,14,42,,,,,,,,,,5.1,3.8,3.4,4*36
$GPGSV,2,1,06,07,39,061,19,08,12,052,23,09,12,119,30,13,42,305,,0*6D
$GPGSV,2,2,06,14,60,156,33,15,11,306,,0*63
$BDGSV,1,1,03,09,12,0840,E,1,07,3.8,605.8,M,43.9,M,,*4F
$GNGLL,4238.92078,N,02322.91040,E,200244.000,A,A*43
$GNGSA,A,3,07,08,09,14,,,,,,,,,5.1,3.8,3.4,1*3A
$GNGSA,A,3,09,14,42,,,,,,,,,,5.1,3.8,3.4,4*36
$GPGSV,2,1,06,07,39,061,19,08,12,052,25,09,11,119,30,13,42,305,,0*68
$GPGSV,2,2,06,14,60,156,33,15,11,306,,0*63
$BDGSV,1,1,03,09,12,082,23,14,49,162,31,42,24,152,39,0*45
$GNRMC,200244.000,A,4238.92078,N,02322.91040,E,0.31,0.00,180723,,,A,V*03
```
they are not informative for me now

**Comment by amoxu** [comment]
The logs are from GPS module.

When you placed the order,  Which edition you selected? open edition or standard edition?

**Comment by nmuntyanov** [comment]
> The logs are from GPS module.
> 
> When you placed the order, Which edition you selected? open edition or standard edition?

I've bough here https://www.aliexpress.com/item/1005005734253889.html
OpenEdition VHF
Order placed on: Jun 29, 2023

**Comment by nmuntyanov** [comment]
But there is no "OpenEdition" word on box
![image](https://github.com/Xinyuan-LilyGO/T-TWR/assets/27429845/1369fd31-5bd7-4419-9ec9-d3174db31424)
what is the difference?

**Comment by amoxu** [comment]
> > The logs are from GPS module.
> > 
> > When you placed the order, Which edition you selected? open edition or standard edition?
> 
> I've bough here https://www.aliexpress.com/item/1005005734253889.html
> OpenEdition VHF
> Order placed on: Jun 29, 2023
> 

You need to read about the NOTICE on the product page,  Open edition is a special edition which with blank RF module,  It will be useful only after open source firmwares released,  Which are under very early development stage.

Welcome to pay attention to the progress of M17 and OPENRTX projects.

**Comment by nmuntyanov** [comment]
Got it! Thank you. 
Do you have links on this projects?

**Comment by amoxu** [comment]
> Got it! Thank you. 
> Do you have links on this projects?

https://discord.gg/k4deHPZy

**Comment by nmuntyanov** [comment]
> > Got it! Thank you.
> > Do you have links on this projects?
> 
> For the open-source firmware of the RF module: NiceRF SA868, Below development repository for your Information. https://github.com/OpenRTX/sa8x8-fw

Thank you. I thought there are no firmware for sa868 at all
Can I somehow burn it into module without soldering it? 
As I understand module is Connected to only ESP32 by UART?
Can it be programmed in-system?

**Comment by nmuntyanov** [comment]
> Thank you. I thought there are no firmware for sa868 at all Can I somehow burn it into module without soldering it? As I understand module is Connected to only ESP32 by UART? Can it be programmed in-system?

I guess, i found
It seems CN4 socket is for sa868 programming

**Comment by amoxu** [comment]
> > Thank you. I thought there are no firmware for sa868 at all Can I somehow burn it into module without soldering it? As I understand module is Connected to only ESP32 by UART? Can it be programmed in-system?
> 
> I guess, i found
> It seems CN4 socket is for sa868 programming

Yes, for more details, please refer to the discussions in the discord channel.

**Comment by nmuntyanov** [comment]
> https://discord.gg/k4deHPZy

May you send me new invite? Old one is expired
I had some issues with my discord account before.

**Comment by amoxu** [comment]
> > https://discord.gg/k4deHPZy
> 
> May you send me new invite? Old one is expired
> I had some issues with my discord account before.

https://discord.gg/K4y5DxeBG

you can also following matrix space:
https://matrix.to/#/#openrtx:matrix.org
All the messages are synchronized between matrix and discord.
