### ISSUE TITLE
Frequency tuning

### ISSUE THREAD

**Issue by dnwk** [Xinyuan-LilyGO/T-TWR#7]
For the walkie-talkie example, I am trying to figure out where is it that controls the TX/RX frequency config. I want to be able to tune to 147.240. Currently, if bandwidth is set to 25k, that also make tuning in 25k increment.

**Comment by SpudGunMan** [comment]
is this firmware intended for the VHF unit?

**Comment by SpudGunMan** [comment]
Boop

**Comment by lewisxhe** [comment]
No, it can only be superimposed in increments of 12.5 or 25, which is stated in the specification.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/T-TWR/blob/master/datasheet/SA868%202W%20Embedded%20walkie%20talkie%20moduleV1.3.pdf

**Comment by lyusupov** [comment]
Unlike SA818 and SA828, the **SA868** module _( with NiceRF firmware )_ is a "**12.5 KHz bandwidth only**"  device:

<br>

<img width="718" alt="image" src="https://github.com/Xinyuan-LilyGO/T-TWR/assets/5849637/ab6f5ac9-48c7-4566-a87a-b63c5c9bea5c">
