### ISSUE TITLE
Can't turn on T-TWR 2.0 

### ISSUE THREAD

**Issue by nmuntyanov** [Xinyuan-LilyGO/T-TWR#8]
Hello guys! Can you help me, please.

Version:  2.0, Open edition
I have used it a little bit and now i can't turn it on with pwr button with battery installed.
It works with external power supply and I can turn it on/off with button, and even battery level works (in case when battery + external power supply)

What it can be? Should I replace AXP2101?

**Comment by lewisxhe** [comment]
Can't turn on when using battery alone?

**Comment by nmuntyanov** [comment]
there is some electric noise, PWM i guess, when I press the pwr button

**Comment by lewisxhe** [comment]
Do you have a multimeter? After pressing PWR, does DC1 on both sides of the pin header have 3.3V?

**Comment by lewisxhe** [comment]
If you have the tools, we can continue to find the problem. If not, please contact customer service to see how to proceed.

**Comment by nmuntyanov** [comment]
I have multimeter
Measurements are:
0,52v before and 0,17v after button press

**Comment by lewisxhe** [comment]
Hi， @nmuntyanov 
What I mean is that after pressing the PWR button, is there 3.3V on the pins marked DC1 on both sides of the TWR?

**Comment by nmuntyanov** [comment]
Hi, @lewisxhe 
Just to clarify

If you mean this pin
![2024-01-16 10 16 48](https://github.com/Xinyuan-LilyGO/T-TWR/assets/27429845/d1d7b98a-ba93-4502-823b-330febea5910)

No, there is no 3,3v between DC1  and GND after PWR button is pressed

**Comment by lewisxhe** [comment]
@nmuntyanov 
Okay, I also need to check the following points with you to help me determine the approximate location of the fault:
1. Connect to USB-C alone and you can boot normally
2. After disconnecting the USBC, connect the battery and press the PWR button for 1 second, but the computer cannot be turned on.
3. After plugging in the battery and then plugging in the USBC, the phone can be turned on. After turning on the phone, disconnect the USBC. Will it continue to be turned on?

**Comment by nmuntyanov** [comment]
@lewisxhe 
1 It boots normally
2 Yes, computer cannot be turned on
3 No, it powered off once I disconnected USBC

**Comment by lewisxhe** [comment]
@nmuntyanov  
Please connect the battery, disconnect the USB, and measure whether there is voltage at these two points.
![image](https://github.com/Xinyuan-LilyGO/T-TWR/assets/22990954/060d6deb-8772-44bd-9b4b-5c03d98b6300)

**Comment by lewisxhe** [comment]
If no voltage is measured, please short-circuit these two points. Please note that short-circuiting these two points means there is no reverse polarity protection. Please confirm the battery polarity.
![image](https://github.com/Xinyuan-LilyGO/T-TWR/assets/22990954/17178c25-71c5-40c4-bb32-45adb7a1835f)

**Comment by lewisxhe** [comment]
If it uses USB power supply, can it be shut down by long pressing PWR?

**Comment by nmuntyanov** [comment]
Yes, it can

**Comment by lewisxhe** [comment]
1. When using USBC for power supply, you can use the PWR button to shut down. This indicates that the connection between the button and the PMU is normal, and the button circuit fault is eliminated.
2. If there is battery voltage at both ends of the measurement capacitor, it means that the battery voltage has reached the PMU input terminal.

After the above diagnosis, I judged that the internal power switching path of the PMU was damaged. This is a situation I have never encountered before. The only solution is to replace the PMU.

If it is still within the warranty period, please contact the salesperson for a replacement.

**Comment by nmuntyanov** [comment]
Thank you for support. Will contact the seller

**Comment by nmuntyanov** [comment]
@lewisxhe
Hello once agin
I've tried to replace PMU with new one and there was no effect. 

I've have studied battery circuit and your recommendations once again and found that Q3 is not working.
Can you tell me with what I can replace it? Can't find it's name in schema.

**Comment by lewisxhe** [comment]
N-channel MOSFET, using AO3400, you can also use other 3400 to replace

**Comment by nmuntyanov** [comment]
Thank you, it works
