### ISSUE TITLE
Following build instructions aren't working for Visual Studio Code

### ISSUE THREAD

**Issue by jasonthenderson** [Xinyuan-LilyGO/T-TWR#9]
I followed the Visual Studio Code build instructions exactly and am getting this error - any ideas?

Processing uhf_band (platform: espressif32; framework: arduino; board: esp32s3box)
--------------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'esp32s3box'

 *  The terminal process "C:\Users\jason\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: C:\Users\username\.platformio\penv\Scripts\platformio.exe run 

Processing uhf_band (platform: espressif32; framework: arduino; board: esp32s3box)
--------------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'esp32s3box'

 *  The terminal process "C:\Users\username\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by lewisxhe** [comment]
The location of esp32s3box is located in the platformio boards directory. If it cannot be found, your platformio installation may not be completed.
https://github.com/platformio/platform-espressif32/blob/develop/boards/esp32s3box.json
